### ISSUE TITLE
Feature requests 

### ISSUE THREAD

**Issue by HolyBugx** [Sh1Yo/x8#1]
Hello Sh1Yo,

Just read the article about x8 and I'm interested to test it out. although in my first glance I saw that there are 2 needs in this tool.

- The text output is not really useful as if we want to quickly check or if we want to pipe into other tools, it would be nicer to have it as a set of parameters and chunks.

So in this case instead of something like:

`GET https://redacted.com/endpoint?%s % code, email, userid` 

We can have:

` https://redacted.com/endpoint?code=123&email=456&userid=789` 

Which is way easier to use in the future.

- The input file support so we can use a list of URLs as an input.

Thanks for the nice tool :)

Kind Regards,
HolyBugx

**Comment by Sh1Yo** [comment]
Hi. The output format needs to be reworked. Thanks for the reminder. Regarding input files, I don't think that this is a necessary feature because it is possible to do this from your terminal with something like this:
```bash
while read url; do x8 -u $url -w wordlist; done < urls.txt
```

**Comment by 0xspade** [comment]
@Sh1Yo,

One more thing, the tool should allow the users to parse a list of URLs or it can be piped to another tool (like gau).

**Comment by Sh1Yo** [comment]
Added new output formats in v2.2.0.
