### ISSUE TITLE
i got this error when i try to run it 

### ISSUE THREAD

**Issue by Sy3Omda** [Sh1Yo/x8#12]
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Custom { kind: Other, error: "error reading DNS system conf: Error parsing resolv.conf: InvalidIp(35, AddrParseError)" } }', src/main.rs:98:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by meweez** [comment]
I have this problem too. 
can you please say how did you fix it?

**Comment by Sh1Yo** [comment]
@meweez, The problem is related to dns resolution. If you believe, that dns is correctly configured on your device, try to use --disable-trustdns flag.
