### ISSUE TITLE
dose not get the same result as other tools

### ISSUE THREAD

**Issue by Sy3Omda** [Sh1Yo/x8#13]
Hi,
i am trying to test effective of using it to enumerate hidden params either in POST or GET request.
so i am running the following command but did not get the desired output as i am getting it from other tools.
```
x8 -u "http://testphp.vulnweb.com/login.php" -X GET --as-body -w ~/tools/Arjun/arjun/db/params.txt -O request -o x8-get.txt
```
or even POST request !!

**Comment by Sh1Yo** [comment]
I have already answered this question in issue #9:
> As you can check yourself, the response does not depend on provided parameters(uname, pass), so it is impossible to detect whether they are present or not.
