### ISSUE TITLE
support parsing from file arjument and append output

### ISSUE THREAD

**Issue by Sy3Omda** [Sh1Yo/x8#14]
Hi,

i see the current argument `-u` which is accepting url as input.
so could it support `-file` for example for multiple URLs per file.

One more thing as temp workaround i'm running it via xargs loop BUT unfortunately it dose not append output it's overwrite the previous output
```
xargs -n1 -P 10 -I {} sh -c "x8 -u {} -O url -o out-x8.txt -c 50" < file-urls.txt
```
the problem with that loop it dose not append the found results to `out-x8.txt`

**Comment by Sh1Yo** [comment]
If you want to save everything in one file just use `>` or `tee` to redirect the output to the file.

**Comment by Sy3Omda** [comment]
That would be possible if u have silent argument to just get output cleaned, but
How come i will append output to file using whatever `>>` or `tee -a` if the tool runtime output dose not contains the desired output!!

**Comment by Sy3Omda** [comment]
@Sh1Yo before closing issue just make sure u offer a practical solution

**Comment by bugbaba** [comment]
You can append the url to the output file name using `{}` to create sepreate output file for each url and then combine all of them in a single file.

>@Sh1Yo before closing issue just make sure u offer a practical solution

You need to focus on learning the shell basics instead of asking others to solve **YOUR** personal problem for free.

**Comment by Sh1Yo** [comment]
I will give it a thought later.

**Comment by Sh1Yo** [comment]
The --append option is added in v3.2.0.

**Comment by cyb3rsalih** [comment]
Hi!
`x8 -w wordlist/parameters.txt -u redacted.com --append --output out.txt` gives error

error: Found argument '--append' which wasn't expected, or isn't valid in this context
