### ISSUE TITLE
installaing issue in parrot os

### ISSUE THREAD

**Issue by defaultertech** [Sh1Yo/x8#16]
', /home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.72/build/find_normal.rs:180:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Sh1Yo** [comment]
Do you have openssl installed? https://docs.rs/openssl/0.10.16/openssl/#automatic

**Comment by defaultertech** [comment]
yeah parrot alerady pre install openssl

**Comment by Sh1Yo** [comment]
Then are there any additional errors? Also, what are your kernel and rust versions

**Comment by Sh1Yo** [comment]
Closed due to no additional response being provided.
