### ISSUE TITLE
error ssl  verification

### ISSUE THREAD

**Issue by Ph33rr** [Sh1Yo/x8#19]
Hello,

danger_disable_hostname_verification() some website use old ssl cert or wrong ..etc
better use this func thank you

reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(555)), port: None, path: "", query: Some(""), fragment: None }, source: hyper::Error(Connect, Custom { kind: Other, error: "invalid dnsname" }) }

**Comment by Sh1Yo** [comment]
Hi. Thanks for noticing. I will take a look into this.

**Comment by Sh1Yo** [comment]
Hi. Can you provide an example? I've run the tool on some test domains from `https://badssl.com/` and didn't receive any error. Looks like it's not a cert but something's wrong with your dns.

**Comment by Ph33rr** [comment]
try ip 

./x8 -u https://184.25.56.69/

**Comment by Sh1Yo** [comment]
Thanks for the follow up. Looks like it's the limitation of a library that I use for https connections - https://github.com/rustls/hyper-rustls/issues/56. I will check whether I can do something with it or not.

**Comment by Sh1Yo** [comment]
Hi @RahmatQurishi, in case it's a persistent problem - check your `/etc/resolv.conf` and check that there's valid nameserver entries. In case there's something wrong with the file - you can add the following nameservers and try to rerun the tool:
```
nameserver 1.1.1.1
nameserver 1.0.0.1
```

**Comment by RahmatQurishi** [comment]
ok thank you so much

**Comment by arthur4ires** [comment]
I'm having the same problem and following the thread.

**Comment by netwons** [comment]
I'm having the same problem and following the thread.

```
[!] https://enroll.bbbb.com/mobile?%s reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("enroll.bbbb.com")), port: None, path: "/mobile", query: Some(""), fragment: None }, source: TimedOut }
[~] error at the https://enroll.bbbb.com/mobile?%s observed. Wait 50 sec and repeat.

```

**Comment by Sh1Yo** [comment]
Hi @netwons, it's another error regarding timeout issues. The site doesn't respond to requests at all:
```
curl https://enroll.bbbb.com/mobile

curl: (28) Failed to connect to enroll.bbbb.com port 443 after 130203 ms: Connection timed out
```

**Comment by netwons** [comment]
@Sh1Yo 
this is run https://enroll.zellepay.com/mobile

**Comment by Sh1Yo** [comment]
Hi @arthur4ires and @RahmatQurishi,

I am unable to reproduce the issue in the latest versions of the tool. Can you confirm?

**Comment by arthur4ires** [comment]
Hi @Sh1Yo , I hope you're okay :)

I saw your update, thank you very much! We were unable to reproduce this issue. What happened was that it was not possible to install x8 through conda.
