### ISSUE TITLE
Read wordlist asynchronously

### ISSUE THREAD

**Issue by amiremohamadi** [Sh1Yo/x8#22]
when it comes to piping commands in order to read the word list (file & stdin), doing it asynchronously would be more efficient. consider sth like [CeWL](https://github.com/digininja/CeWL) which extracts words from a website and creates a word list. so instead of waiting for the whole output we can read them asynchronously as they're generated.
I guess this can be done with little effort as `x8` itself has an `async` architecture.

**Comment by Sh1Yo** [comment]
After taking another look at this, I've realized that making the necessary architecture changes would be a massive undertaking. Even if we were able to make these changes, the resulting speed improvements would be relatively minor. Therefore, I've decided to close this as "won't fix" for now.
