### ISSUE TITLE
Isn't there a parameter property for targets.txt?

### ISSUE THREAD

**Issue by Phoenix1112** [Sh1Yo/x8#24]
hello. thanks for this project... i have targets.txt .. I couldn't find a parameter where it can read all url addresses with file. With the -u parameter, I cannot manually type all the url addresses one by one. please reply if you know a way to read url addresses from list. If there is no such feature, can you add this feature?

**Comment by Sh1Yo** [comment]
It will be implemented the next update. For now you can use shell scripting like
`for i in `cat target.txt`; do x8 -u $i; done`
