### ISSUE TITLE
Add support for openssl v3.0

### ISSUE THREAD

**Issue by CyberGhazi786** [Sh1Yo/x8#26]
Hello Sir,

How to solve this issue in ARCH LINUX, Please help :-)
#####################################################################################################
$ sudo pacman -S x8
[sudo] password for cyberghazi786: 
error: could not register 'multilib' database (database already registered)
error: could not register 'multilib' database (database already registered)
error: could not register 'multilib' database (database already registered)
error: could not register 'multilib' database (database already registered)
resolving dependencies...
looking for conflicting packages...

Package (1)   New Version    Net Change

blackarch/x8  113.5f3b3cd-1    7.59 MiB

Total Installed Size:  7.59 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                               [--------------------------------] 100%
(1/1) checking package integrity                             [--------------------------------] 100%
(1/1) loading package files                                  [--------------------------------] 100%
(1/1) checking for file conflicts                            [--------------------------------] 100%
:: Processing package changes...
(1/1) installing x8                                          [--------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[cyberghazi786@cyberghazi786-vmwarevirtualplatform bin]$ x8
x8: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

#######################################################################################################

**Comment by Sh1Yo** [comment]
Try to install openssl: https://bbs.archlinux.org/viewtopic.php?id=281012

**Comment by noraj** [comment]
cf. https://github.com/BlackArch/blackarch/issues/3592

Yeah we'll temporarily add `openssl-1.1` as a workaround but in the long term x8 should support `openssl` (v 3.0) too.

**Comment by Sh1Yo** [comment]
Thanks for an update. I will do something about it

**Comment by Sh1Yo** [comment]
Hi @noraj, 

the latest v4.1.0  x86_64-linux-x8.gz should work with openssl v3.
