### ISSUE TITLE
pacman Error

### ISSUE THREAD

**Issue by Matin7697** [Sh1Yo/x8#27]
Hello dear ;
When I want to install x8, I face such a problem and I also have openssl3, which I put at the end of the specification page,

➜  ~ pacman -S x8
sudo: unable to resolve host (my host provider name): Name or service not known
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package x8
-----------------------------------
and:
➜  ~ pacman -S x8    
sudo: unable to resolve host (my host provider name): Name or service not known
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package x8
-----------------------------------
"OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
built on: Thu Oct 27 17:06:56 2022 UTC
platform: debian-amd64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -ffile-prefix-map=/build/openssl-WsPfAX/openssl-3.0.2=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-3"
MODULESDIR: "/usr/lib/x86_64-linux-gnu/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0xfffa32034f8bffff:0x9c4fbb"
--------------------------------------------------------------
Thank you.

**Comment by Sh1Yo** [comment]
The latest release contains a tool compatible with openssl v3.
