### ISSUE TITLE
--replay-proxy issue ? 

### ISSUE THREAD

**Issue by mgcfish** [Sh1Yo/x8#30]
Hello,

I have been trying to use the --replay-proxy but without any success  
Example : x8 -u 'https://www.test.com' -X GET POST -c 20  -w parameters-lowercase-all.txt --replay-proxy http://127.0.0.1:8080  

wondering if there is an issue with the foonctionality or if i am using it wrong 

Kr

**Comment by Sh1Yo** [comment]
Hi,

Looks like there's indeed a bug. Thanks for reaching out.

**Comment by Sh1Yo** [comment]
Fixed in 18afd9080fbbd0a0ba95e0b8885dc0c6eb826d7b. The new version of the tool with this change will be published in a few days.
