### ISSUE TITLE
как установить?

### ISSUE THREAD

**Issue by sasholy** [Sh1Yo/x8#37]
Привет,  Burp стоит на 11 винде\64 - скачал для винды x86-windown-x8.zip у тебя с репы - неработает из-за рязрядности винды? спс
![6745](https://user-images.githubusercontent.com/35170306/225686862-0a341c7e-b8ff-4e5c-ad1e-44a58f6553bc.png)

**Comment by Sh1Yo** [comment]
Попробуй запустить из консоли. Может с расширением проблема или ты настроил его неверно.

**Comment by sasholy** [comment]
хотелось бы не бегать то в burp то в Kali, ок розберусь. И еще вопросик по теме, твое мнение о GAP -?

**Comment by Sh1Yo** [comment]
Не имею понятия, что это такое.
