### ISSUE TITLE
How to Get the requests with identified parmeters.

### ISSUE THREAD

**Issue by neetech18** [Sh1Yo/x8#4]
After running this tool where can i get the requests which contains the below identified parameters. Can you please help me to understand this please.

![image](https://user-images.githubusercontent.com/12570891/124896024-b5368800-dffa-11eb-93c7-4eca53022ffc.png)

**Comment by Sh1Yo** [comment]
The tool doesn't save requests. But you can save it on your own using something like zap/burpsuite with the `--replay-proxy` flag.
