### ISSUE TITLE
can not write the output to a file

### ISSUE THREAD

**Issue by oldDuDe124** [Sh1Yo/x8#40]
hi 
i'm using the following command:

x8 -u https://example.com -o output.txt -O url -w params.txt -m 25 --follow-redirects --verbose 2 --reflected-only --verify

but after finishing the scan , the output.txt file is empty and the results are not saved in the file , i'm using the latest version(4.2.2)

i'd appericate it if you can help me out!

**Comment by Sh1Yo** [comment]
Hi, its a duplicate of https://github.com/Sh1Yo/x8/issues/28

**Comment by amiremami** [comment]
I'm using --reflected-only and I still see changes reflection on terminal, do have this problem too? @oldDuDe124
