### ISSUE TITLE
Wordlist with special chars may cause errors on crates.io version of the tool

### ISSUE THREAD

**Issue by sp1nn4k3r** [Sh1Yo/x8#41]
5/18     thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: http::Error(InvalidHeaderName)

Is possible to override this error? Or maybe a flag to clean the wordlist before bf starting?

Thank you

**Comment by Sh1Yo** [comment]
Hi, thanks for the issue. Can you provide the word that causes this error and the version(main or from crates.io) of the tool?

**Comment by sp1nn4k3r** [comment]
Latest version of the tool main version installed with "cargo install x8" cargo version = cargo 1.70.0 (ec8a8a0ca 2023-04-25). The word I am not sure but it gives that error also with Wordlists provided by you in the readme. Started to think is a cargo release problem. 

Thanks

**Comment by sp1nn4k3r** [comment]
Error keep going with --header flag and without it.

**Comment by sp1nn4k3r** [comment]
Gzip main version go well on parameters but stop on --headers flag without error.![IMG_20230604_195645.jpg](https://github.com/Sh1Yo/x8/assets/48521193/a66198c1-10cd-4941-8258-4cdfb6b6cf9e)

**Comment by Sh1Yo** [comment]
Thanks, I'll check it in my free time and return to this issue. For now, you can manually remove the words with special characters from the wordlist. I think they're the main reason of the error.

**Comment by sp1nn4k3r** [comment]
Perfect. Thank you again

**Comment by Sh1Yo** [comment]
> Gzip main version go well on parameters but stop on --headers flag without error.![IMG_20230604_195645.jpg](https://user-images.githubusercontent.com/48521193/243198345-a66198c1-10cd-4941-8258-4cdfb6b6cf9e.jpg)

It's fine. Sometimes a server may refuse to send an answer or send it after a delay in case some special or invalid headers are sent. You can try to decrease the value of `--timeout` if it bothers you.

**Comment by mAminP** [comment]
Hi 

I also encounter this error when I use the following wordlist. I tried to remove some characters from the wordlist, but I didn't get any result


wordlsit:
https://wordlists-cdn.assetnote.io/data/automated/httparchive_parameters_top_1m_2023_05_28.txt

Error: 
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: http::Error(InvalidUri(InvalidUriChar))', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/x8-4.3.0/src/network/request.rs:325:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```


commad:
```
x8 -u <domain.tld> -w <wordlist> -c 1 -m 20
```

**Comment by mAminP** [comment]
Hi again 

I used this command to fix the problem.
The problem is solved now, but I think this method makes me miss some words

`cat <WORDLIST> |  jq -Rr @uri |  tee <NEW_WORDLIST>.txt`

**Comment by dualfade** [comment]
^^ confirmed worked for me as well.

**Comment by sp1nn4k3r** [comment]
Wow thank you :)

Il lun 12 giu 2023, 07:48 Mohammad Amin Pasban ***@***.***>
ha scritto:

**Comment by sp1nn4k3r** [comment]
Thank you

Il gio 22 giu 2023, 15:28 Mohammad Amin Pasban ***@***.***>
ha scritto:

**Comment by Sh1Yo** [comment]
Hi @sp1nn4k3r and @mAminP. Please, don't try to use the `--encode` flag to solve the issue. It encodes the whole query and therefore the server won't recognize the parameters. I'll try to fix the issue this week and return with an update

**Comment by sp1nn4k3r** [comment]
Ok thank you again. Btw good job for this awesome tool ✅💪.

Il mar 27 giu 2023, 20:47 Alexander Mironov ***@***.***> ha
scritto:

**Comment by Sh1Yo** [comment]
The new version of the tool from crates.io (that gets installed with `cargo install`) now urlencodes parameters' keys and ignores invalid headers that solves the issue.
