### ISSUE TITLE
Error while cargo install and cargo build

### ISSUE THREAD

**Issue by szybnev** [Sh1Yo/x8#42]
**Kali Linux 2023.2 in VMware Workstation; Full updated** 

┌──(kali㉿kali)-[~/tools/x8]
└─$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/kali/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.70.0 (90c541806 2023-05-31)

┌──(kali㉿kali)-[~/tools/x8]
└─$ cargo build --release                
    Updating git repository `https://github.com/raw-http/http`
    Updating git repository `https://github.com/raw-http/reqwest`
    Updating git repository `https://github.com/raw-http/rust-url`
    Updating git repository `https://github.com/raw-http/serde_urlencoded`
    Updating git repository `https://github.com/raw-http/cookie_store`
    Updating git repository `https://github.com/raw-http/h2`
    Updating git repository `https://github.com/raw-http/http-body`
    Updating git repository `https://github.com/raw-http/hyper`
    Updating git repository `https://github.com/raw-http/hyper-rustls`
    Updating git repository `https://github.com/raw-http/hyper-tls`
  Downloaded tokio-macros v1.8.2
  Downloaded time-core v0.1.0
  Downloaded futures-core v0.3.27
  Downloaded openssl-macros v0.1.0
  Downloaded data-encoding v2.3.3
  Downloaded pkg-config v0.3.26
  Downloaded futures-sink v0.3.27
  Downloaded futures-task v0.3.27
  Downloaded futures-executor v0.3.27
  Downloaded futures-io v0.3.27
  Downloaded getrandom v0.2.8
  Downloaded futures-macro v0.3.27
  Downloaded proc-macro-hack v0.5.20+deprecated
  Downloaded quote v1.0.26
  Downloaded time-macros v0.2.8
  Downloaded log v0.4.17
  Downloaded console v0.15.5
  Downloaded futures-channel v0.3.27
  Downloaded unicode-ident v1.0.8
  Downloaded once_cell v1.17.1
  Downloaded openssl-sys v0.9.83
  Downloaded miniz_oxide v0.6.2
  Downloaded ipnet v2.7.1
  Downloaded futures v0.3.27
  Downloaded indicatif v0.17.3
  Downloaded serde_derive v1.0.158
  Downloaded proc-macro2 v1.0.53
  Downloaded tracing-core v0.1.30
  Downloaded base64 v0.21.0
  Downloaded flate2 v1.0.25
  Downloaded async-compression v0.3.15
  Downloaded serde v1.0.158
  Downloaded portable-atomic v0.3.19
  Downloaded tokio-util v0.7.7
  Downloaded time v0.3.20
  Downloaded aho-corasick v0.7.20
  Downloaded mio v0.8.6
  Downloaded serde_json v1.0.94
  Downloaded futures-util v0.3.27
  Downloaded syn v2.0.10
  Downloaded openssl v0.10.48
  Downloaded regex v1.7.3
  Downloaded rustls v0.20.8
  Downloaded regex-syntax v0.6.29
  Downloaded tokio v1.26.0
  Downloaded libc v0.2.140
  Downloaded 46 crates (4.5 MB) in 1.15s
   Compiling libc v0.2.140
   Compiling proc-macro2 v1.0.53
   Compiling unicode-ident v1.0.8
   Compiling quote v1.0.26
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.109
   Compiling memchr v2.5.0
   Compiling log v0.4.17
   Compiling cc v1.0.79
   Compiling pin-project-lite v0.2.9
   Compiling futures-core v0.3.27
   Compiling lock_api v0.4.9
   Compiling smallvec v1.10.0
   Compiling once_cell v1.17.1
   Compiling parking_lot_core v0.9.7
   Compiling scopeguard v1.1.0
   Compiling bytes v1.4.0
   Compiling tokio v1.26.0
   Compiling slab v0.4.8
   Compiling futures-sink v0.3.27
   Compiling futures-channel v0.3.27
   Compiling futures-task v0.3.27
   Compiling socket2 v0.4.9
   Compiling signal-hook-registry v1.4.1
   Compiling mio v0.8.6
   Compiling num_cpus v1.15.0
   Compiling parking_lot v0.12.1
   Compiling syn v2.0.10
   Compiling futures-util v0.3.27
   Compiling itoa v1.0.6
   Compiling futures-io v0.3.27
   Compiling tinyvec_macros v0.1.1
   Compiling pin-utils v0.1.0
   Compiling tinyvec v1.6.0
   Compiling ring v0.16.20
   Compiling unicode-bidi v0.3.13
   Compiling pkg-config v0.3.26
   Compiling spin v0.5.2
   Compiling fnv v1.0.7
   Compiling untrusted v0.7.1
   Compiling http v0.2.8 (https://github.com/raw-http/http#399dc9e6)
   Compiling tracing-core v0.1.30
   Compiling openssl-sys v0.9.83
   Compiling unicode-normalization v0.1.22
error: failed to run custom build command for `openssl-sys v0.9.83`

Caused by:
  process didn't exit successfully: `/home/kali/tools/x8/target/release/build/openssl-sys-c887e3d82287a627/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "openssl"` did not exit successfully: exit status: 1
  error: could not find system library 'openssl' required by the 'openssl-sys' crate

  --- stderr
  Package openssl was not found in the pkg-config search path.
  Perhaps you should add the directory containing `openssl.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'openssl', required by 'virtual:world', not found

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.83

  ', /home/kali/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.83/build/find_normal.rs:190:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by Sh1Yo** [comment]
Either read the error and search for the solution on similar github issues or just download the tool from releases.
