### ISSUE TITLE
Issue to run after installation

### ISSUE THREAD

**Issue by abdulx01** [Sh1Yo/x8#46]
I have installed but having issue to run. 

![image](https://github.com/Sh1Yo/x8/assets/61224688/22dd1748-9f42-4340-b635-fa0d994aca96)

**Comment by hackeyz** [comment]
Hello. has this issued been fixed? 
Note that you are to run the command `x8`, or better still `x8 -h` to confirm if it is successfully working

**Comment by Sh1Yo** [comment]
Try `~/R/x8/target/release/x8 ` instead of `8x`

**Comment by Sh1Yo** [comment]
you can check readme for additional installation steps now
