### ISSUE TITLE
INSTALLATION ERROR!

### ISSUE THREAD

**Issue by ivasugarg** [Sh1Yo/x8#5]
![ERORR-X8](https://user-images.githubusercontent.com/51096893/125033828-aeccfe00-e044-11eb-96ee-64582f1d237b.PNG)

**Comment by Sh1Yo** [comment]
Can you provide some addictional info such as OS and rust versions?

**Comment by ivasugarg** [comment]
RUSTC->1.45.1 & OS -> ubuntu 20.04.1

**Comment by Sh1Yo** [comment]
Socket2 requires rust 1.46+. Try to update rustc or install x8 directly from releases.
