### ISSUE TITLE
Feature request: headers and headers' values discovery

### ISSUE THREAD

**Issue by iamRjarpan** [Sh1Yo/x8#7]
Hy, I love your tool can you add header and cookie bruteforce also? It will replace param miner and other tools also

**Comment by Sh1Yo** [comment]
Hi, thanks for the reminder. It was on my TODO list for a long time. I will work on it in my free time.

**Comment by Sh1Yo** [comment]
Hi @iamRjarpan, I've released a beta version with these features - https://github.com/Sh1Yo/x8/releases/tag/v3.0.0-beta.1

**Comment by Sh1Yo** [comment]
Implemented in v3.0.0.
