### ISSUE TITLE
Regex for JSON

### ISSUE THREAD

**Issue by mr0xE** [Sh1Yo/x8#8]
Great tool,

Can you add a regex filter for JSON parameters. 
e.g regex-positive to look for regex if the json endpoint is available and regex-negative to exclude all those parameters if endpoint is unavailable.

**Comment by Sh1Yo** [comment]
Hi, can you add some additional explanations and/or some examples? I am not sure what exactly you are suggesting.

**Comment by mr0xE** [comment]
In my hunting when brute forcing for endpoints in JSON, i normally enter a random impossible key like *idontexist* and see what errors it may spit out.

Then i add that random key to other keys that are present like "username" "email" and see what errors it spits out.

Then i pass keys that are specified in the documentation and see what output i get.

**Comment by Sh1Yo** [comment]
So you want something like `-mr` and `-fr` in ffuf? I will think about it.

**Comment by Sh1Yo** [comment]
I don't think it would be useful as the tool already can pretty good find parameters in json on its own.
