### ISSUE TITLE
output as raw request

### ISSUE THREAD

**Issue by Sy3Omda** [Sh1Yo/x8#9]
amazing tool, really 
could you add support to output the request as raw so it can be imported directly to any other tool?
example
```
POST /someendpoint HTTP/1.1
Host: example.com
Connection: close
Accept: */*
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103
Content-Type: application/json

{...discovered params here}
```

Thanks

**Comment by Sh1Yo** [comment]
Added in v3.0.1

**Comment by Sy3Omda** [comment]
woow this was fast @Sh1Yo 
thank u for quick response
but i need to point to two things 
1- the request output is malformed with the url itself in the beginning which is not the right syntax  of RAW request as shown 

![2021-08-11 16_48_37-Window](https://user-images.githubusercontent.com/48482029/129052205-4319927e-ea13-4b18-aa1f-9bbdff911817.png)

2- while i was testing the tool in that vulnerable site it did not detect the params in login form !!
could i misused the tool OR there is another argument has to be define ?

**Comment by Sh1Yo** [comment]
1. Thanks for the remark. I will fix it.
2. As you can check yourself, the response does not depend on provided parameters(uname, pass), so it is impossible to detect whether they are present or not.

**Comment by Sy3Omda** [comment]
Thx for the new fix
just i want to hint to something
there is a char `&` added to end of every request enumerated and found params in it as shown 

![2021-08-11_22-22](https://user-images.githubusercontent.com/48482029/129098107-87e14a55-89b7-45cb-92d3-599a53aca1c0.png)

**Comment by Sy3Omda** [comment]
thx for the fix @Sh1Yo
